# Generated by Django 5.2.17 on 2026-09-09 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer / Homeowner'), ('provider', 'Service Provider / Professional')], default='customer', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('city', models.CharField(blank=True, default='Kannur', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('bio', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether this provider has been verified.')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('free', 'Free Plan'), ('pro', 'Pro Plan (₹399/month)')], default='free', max_length=50)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.userprofile')),
            ],
        ),
    ]
