# Generated by Django 5.2.17 on 2026-09-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payout_preference',
            field=models.CharField(choices=[('upi', 'UPI Transfer'), ('bank', 'Bank Transfer')], default='upi', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payout_status',
            field=models.CharField(choices=[('not_configured', 'Not Configured'), ('configured', 'Configured'), ('verification_required', 'Verification Required'), ('ready', 'Ready for Payout')], default='not_configured', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payout_upi_id',
            field=models.CharField(blank=True, default='', help_text='Private provider UPI ID for electronic settlement disbursements.', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payout_upi_name',
            field=models.CharField(blank=True, default='', help_text='Beneficiary name associated with UPI ID.', max_length=150),
        ),
    ]
