# Generated by Django 5.2.17 on 2026-09-10 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_revenuetransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_created', 'New Booking Request'), ('booking_accepted', 'Booking Accepted'), ('booking_declined', 'Booking Declined'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Service Completed'), ('review_received', 'New Review Received'), ('subscription_activated', 'Pro Subscription Activated'), ('featured_listing_activated', 'Service Featured')], max_length=35)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='services.booking')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
