# Generated by Django 5.2.17 on 2026-09-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuetransaction',
            name='evidence_note',
            field=models.TextField(blank=True, help_text='Auditor notes regarding banking reference, invoice, or screenshot verification.'),
        ),
        migrations.AddField(
            model_name='revenuetransaction',
            name='has_evidence',
            field=models.BooleanField(default=False, help_text='True if external proof (bank statement, customer receipt) has been inspected.'),
        ),
        migrations.AddField(
            model_name='revenuetransaction',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='True if synthetic demonstration/seed transaction; False if genuine pilot record.'),
        ),
        migrations.AddField(
            model_name='revenuetransaction',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date genuine payment was credited in bank/account.', null=True),
        ),
        migrations.AddField(
            model_name='revenuetransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI / QR Transfer'), ('bank_transfer', 'Bank IMPS/NEFT'), ('card', 'Debit / Credit Card'), ('other', 'Other Digital Payment'), ('cash', 'Cash (Ineligible for RGM)')], help_text='Actual electronic payment method used.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='revenuetransaction',
            name='transaction_reference',
            field=models.CharField(blank=True, help_text='Bank/UPI UTR or transfer reference number.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='revenuetransaction',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Administrative audit verification state.', max_length=20),
        ),
        migrations.AlterField(
            model_name='revenuetransaction',
            name='revenue_type',
            field=models.CharField(choices=[('commission', 'Booking Commission'), ('subscription', 'Pro Subscription'), ('featured', 'Featured Service Listing')], max_length=20),
        ),
    ]
