# Generated by Django 5.2.17 on 2026-09-11 06:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_booking_payment_status_paymenttransaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final payable total locked after materials approval (service + materials).', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='materials_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total approved physical materials and parts reimbursement.', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base price for the agreed service.', max_digits=10),
        ),
        migrations.AddField(
            model_name='providersettlement',
            name='materials_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='providersettlement',
            name='service_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated platform revenue earned on completion (10% of service charge)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_created', 'New Booking Request'), ('booking_accepted', 'Booking Accepted'), ('booking_declined', 'Booking Declined'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Service Completed'), ('review_received', 'New Review Received'), ('subscription_activated', 'Pro Subscription Activated'), ('featured_listing_activated', 'Service Featured'), ('materials_added', 'Materials Proposal Added'), ('materials_approved', 'Materials Approved'), ('materials_rejected', 'Materials Rejected'), ('payment_received', 'Payment Confirmed'), ('refund_processed', 'Payment Refunded')], max_length=35),
        ),
        migrations.CreateModel(
            name='BookingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_image', models.FileField(blank=True, null=True, upload_to='material_receipts/')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_materials', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='services.booking')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
